name: CI

on:
  push:
    branches:
      - main
      - dockerfile-and-gh-actions
  pull_request:
    branches:
      - main
      - dockerfile-and-gh-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4

    - name: Set up Docker
      run: |
        docker build -t file-processing-tests .

    - name: Run tests
      run: |
        docker run --rm file-processing-tests pytest tests/unit
        docker run --rm file-processing-tests pytest tests/integration