name: Run Pytest

on:
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker images
        run: docker build --build-arg DEV=true --build-arg FULL=true -t idp .

      - name: Run Pytest
        run: docker run -i -v $PWD:/srv -w/srv idp pytest tests/ --junit-xml=.test_report.xml

      - name: Generate PyTest report
        uses: test-summary/action@v2
        with:
          paths: .test_report.xml
          show: fail
        if: always()
